// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_option.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProductOption = `-- name: CreateProductOption :one

INSERT INTO product_options (id, product_id, name, position, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, product_id, name, position, created_at, updated_at
`

type CreateProductOptionParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	Name      string    `json:"name"`
	Position  int16     `json:"position"`
}

// -------------------------------------------------------
// product_options
// -------------------------------------------------------
func (q *Queries) CreateProductOption(ctx context.Context, arg CreateProductOptionParams) (ProductOption, error) {
	row := q.db.QueryRowContext(ctx, createProductOption,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Position,
	)
	var i ProductOption
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductOptionValue = `-- name: CreateProductOptionValue :one

INSERT INTO product_option_values (id, product_option_id, value, position, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, product_option_id, value, position, created_at, updated_at
`

type CreateProductOptionValueParams struct {
	ID              uuid.UUID `json:"id"`
	ProductOptionID uuid.UUID `json:"product_option_id"`
	Value           string    `json:"value"`
	Position        int16     `json:"position"`
}

// -------------------------------------------------------
// product_option_values
// -------------------------------------------------------
func (q *Queries) CreateProductOptionValue(ctx context.Context, arg CreateProductOptionValueParams) (ProductOptionValue, error) {
	row := q.db.QueryRowContext(ctx, createProductOptionValue,
		arg.ID,
		arg.ProductOptionID,
		arg.Value,
		arg.Position,
	)
	var i ProductOptionValue
	err := row.Scan(
		&i.ID,
		&i.ProductOptionID,
		&i.Value,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductOption = `-- name: DeleteProductOption :execresult
DELETE FROM product_options
WHERE id = $1
`

func (q *Queries) DeleteProductOption(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProductOption, id)
}

const deleteProductOptionValue = `-- name: DeleteProductOptionValue :execresult
DELETE FROM product_option_values
WHERE id = $1
`

func (q *Queries) DeleteProductOptionValue(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProductOptionValue, id)
}

const getProductOptionByID = `-- name: GetProductOptionByID :one
SELECT id, product_id, name, position, created_at, updated_at
FROM product_options
WHERE id = $1
`

func (q *Queries) GetProductOptionByID(ctx context.Context, id uuid.UUID) (ProductOption, error) {
	row := q.db.QueryRowContext(ctx, getProductOptionByID, id)
	var i ProductOption
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductOptionValueByID = `-- name: GetProductOptionValueByID :one
SELECT id, product_option_id, value, position, created_at, updated_at
FROM product_option_values
WHERE id = $1
`

func (q *Queries) GetProductOptionValueByID(ctx context.Context, id uuid.UUID) (ProductOptionValue, error) {
	row := q.db.QueryRowContext(ctx, getProductOptionValueByID, id)
	var i ProductOptionValue
	err := row.Scan(
		&i.ID,
		&i.ProductOptionID,
		&i.Value,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductOptionValuesByOptionID = `-- name: GetProductOptionValuesByOptionID :many
SELECT id, product_option_id, value, position, created_at, updated_at
FROM product_option_values
WHERE product_option_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) GetProductOptionValuesByOptionID(ctx context.Context, productOptionID uuid.UUID) ([]ProductOptionValue, error) {
	rows, err := q.db.QueryContext(ctx, getProductOptionValuesByOptionID, productOptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductOptionValue{}
	for rows.Next() {
		var i ProductOptionValue
		if err := rows.Scan(
			&i.ID,
			&i.ProductOptionID,
			&i.Value,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductOptionsByProductID = `-- name: GetProductOptionsByProductID :many
SELECT id, product_id, name, position, created_at, updated_at
FROM product_options
WHERE product_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) GetProductOptionsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductOption, error) {
	rows, err := q.db.QueryContext(ctx, getProductOptionsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductOption{}
	for rows.Next() {
		var i ProductOption
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductOption = `-- name: UpdateProductOption :one
UPDATE product_options
SET name       = $2,
    position   = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, product_id, name, position, created_at, updated_at
`

type UpdateProductOptionParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Position int16     `json:"position"`
}

func (q *Queries) UpdateProductOption(ctx context.Context, arg UpdateProductOptionParams) (ProductOption, error) {
	row := q.db.QueryRowContext(ctx, updateProductOption, arg.ID, arg.Name, arg.Position)
	var i ProductOption
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
