// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_variant.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const bulkCreateProductVariantOptionValues = `-- name: BulkCreateProductVariantOptionValues :exec
INSERT INTO product_variant_option_values (variant_id, product_option_value_id)
SELECT $1::uuid, UNNEST($2::uuid[])
`

type BulkCreateProductVariantOptionValuesParams struct {
	Column1 uuid.UUID   `json:"column_1"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) BulkCreateProductVariantOptionValues(ctx context.Context, arg BulkCreateProductVariantOptionValuesParams) error {
	_, err := q.db.ExecContext(ctx, bulkCreateProductVariantOptionValues, arg.Column1, pq.Array(arg.Column2))
	return err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (id, product_id, image_id, sku, price, stock, weight, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, product_id, image_id, sku, price, stock, weight, status, created_at, updated_at, deleted_at
`

type CreateProductVariantParams struct {
	ID        uuid.UUID     `json:"id"`
	ProductID uuid.UUID     `json:"product_id"`
	ImageID   *uuid.UUID    `json:"image_id"`
	Sku       string        `json:"sku"`
	Price     string        `json:"price"`
	Stock     int32         `json:"stock"`
	Weight    *string       `json:"weight"`
	Status    VariantStatus `json:"status"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, createProductVariant,
		arg.ID,
		arg.ProductID,
		arg.ImageID,
		arg.Sku,
		arg.Price,
		arg.Stock,
		arg.Weight,
		arg.Status,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageID,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Weight,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProductVariant = `-- name: DeleteProductVariant :execresult
UPDATE product_variants
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteProductVariant(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProductVariant, id)
}

const getProductVariantByID = `-- name: GetProductVariantByID :many
SELECT
    pv.id, pv.product_id, pv.image_id, pv.sku, pv.price, pv.stock, pv.weight, pv.status, pv.created_at, pv.updated_at, pv.deleted_at,
    pov.id AS value_id, pov.product_option_id, pov.value AS value_text, pov.position AS value_position, pov.is_active AS value_is_active, pov.created_at AS value_created_at, pov.updated_at AS value_updated_at
FROM product_variants pv
LEFT JOIN product_variant_option_values pvov ON pvov.variant_id = pv.id
LEFT JOIN product_option_values pov ON pov.id = pvov.product_option_value_id AND pov.deleted_at IS NULL
WHERE pv.id = $1 AND pv.deleted_at IS NULL
`

type GetProductVariantByIDRow struct {
	ID              uuid.UUID      `json:"id"`
	ProductID       uuid.UUID      `json:"product_id"`
	ImageID         *uuid.UUID     `json:"image_id"`
	Sku             string         `json:"sku"`
	Price           string         `json:"price"`
	Stock           int32          `json:"stock"`
	Weight          *string        `json:"weight"`
	Status          VariantStatus  `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       *time.Time     `json:"deleted_at"`
	ValueID         uuid.NullUUID  `json:"value_id"`
	ProductOptionID uuid.NullUUID  `json:"product_option_id"`
	ValueText       sql.NullString `json:"value_text"`
	ValuePosition   sql.NullInt16  `json:"value_position"`
	ValueIsActive   sql.NullBool   `json:"value_is_active"`
	ValueCreatedAt  sql.NullTime   `json:"value_created_at"`
	ValueUpdatedAt  sql.NullTime   `json:"value_updated_at"`
}

func (q *Queries) GetProductVariantByID(ctx context.Context, id uuid.UUID) ([]GetProductVariantByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductVariantByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductVariantByIDRow{}
	for rows.Next() {
		var i GetProductVariantByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ImageID,
			&i.Sku,
			&i.Price,
			&i.Stock,
			&i.Weight,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ValueID,
			&i.ProductOptionID,
			&i.ValueText,
			&i.ValuePosition,
			&i.ValueIsActive,
			&i.ValueCreatedAt,
			&i.ValueUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductVariantsByProductID = `-- name: GetProductVariantsByProductID :many
SELECT
    pv.id, pv.product_id, pv.image_id, pv.sku, pv.price, pv.stock, pv.weight, pv.status, pv.created_at, pv.updated_at, pv.deleted_at,
    pov.id AS value_id, pov.product_option_id, pov.value AS value_text, pov.position AS value_position, pov.is_active AS value_is_active, pov.created_at AS value_created_at, pov.updated_at AS value_updated_at
FROM product_variants pv
LEFT JOIN product_variant_option_values pvov ON pvov.variant_id = pv.id
LEFT JOIN product_option_values pov ON pov.id = pvov.product_option_value_id AND pov.deleted_at IS NULL
WHERE pv.product_id = $1 AND pv.deleted_at IS NULL
ORDER BY pv.created_at DESC
`

type GetProductVariantsByProductIDRow struct {
	ID              uuid.UUID      `json:"id"`
	ProductID       uuid.UUID      `json:"product_id"`
	ImageID         *uuid.UUID     `json:"image_id"`
	Sku             string         `json:"sku"`
	Price           string         `json:"price"`
	Stock           int32          `json:"stock"`
	Weight          *string        `json:"weight"`
	Status          VariantStatus  `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       *time.Time     `json:"deleted_at"`
	ValueID         uuid.NullUUID  `json:"value_id"`
	ProductOptionID uuid.NullUUID  `json:"product_option_id"`
	ValueText       sql.NullString `json:"value_text"`
	ValuePosition   sql.NullInt16  `json:"value_position"`
	ValueIsActive   sql.NullBool   `json:"value_is_active"`
	ValueCreatedAt  sql.NullTime   `json:"value_created_at"`
	ValueUpdatedAt  sql.NullTime   `json:"value_updated_at"`
}

func (q *Queries) GetProductVariantsByProductID(ctx context.Context, productID uuid.UUID) ([]GetProductVariantsByProductIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductVariantsByProductIDRow{}
	for rows.Next() {
		var i GetProductVariantsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ImageID,
			&i.Sku,
			&i.Price,
			&i.Stock,
			&i.Weight,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ValueID,
			&i.ProductOptionID,
			&i.ValueText,
			&i.ValuePosition,
			&i.ValueIsActive,
			&i.ValueCreatedAt,
			&i.ValueUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE product_variants
SET image_id = $2,
    sku = $3,
    price = $4,
    stock = $5,
    weight = $6,
    status = $7,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, product_id, image_id, sku, price, stock, weight, status, created_at, updated_at, deleted_at
`

type UpdateProductVariantParams struct {
	ID      uuid.UUID     `json:"id"`
	ImageID *uuid.UUID    `json:"image_id"`
	Sku     string        `json:"sku"`
	Price   string        `json:"price"`
	Stock   int32         `json:"stock"`
	Weight  *string       `json:"weight"`
	Status  VariantStatus `json:"status"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, updateProductVariant,
		arg.ID,
		arg.ImageID,
		arg.Sku,
		arg.Price,
		arg.Stock,
		arg.Weight,
		arg.Status,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageID,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Weight,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
