// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const activateCategory = `-- name: ActivateCategory :execresult
WITH RECURSIVE ancestors AS (
    SELECT parent.id, parent.parent_id, parent.status, parent.deleted_at, ARRAY[parent.id] AS path
    FROM categories category
    INNER JOIN categories parent ON parent.id = category.parent_id
    WHERE category.id = $1

    UNION ALL

    SELECT parent.id, parent.parent_id, parent.status, parent.deleted_at, child.path || parent.id
    FROM categories parent
    INNER JOIN ancestors child ON parent.id = child.parent_id
    WHERE NOT parent.id = ANY(child.path)
)
UPDATE categories AS category
SET status = 'active',
    version = version + 1,
    updated_at = NOW()
WHERE category.id = $1
  AND category.status = 'draft'
  AND category.version = $2
  AND category.deleted_at IS NULL
  AND (
      category.parent_id IS NULL
      OR NOT EXISTS (SELECT 1 FROM ancestors WHERE ancestors.status <> 'active' OR ancestors.deleted_at IS NOT NULL)
  )
`

type ActivateCategoryParams struct {
	ID      uuid.UUID `json:"id"`
	Version int64     `json:"version"`
}

func (q *Queries) ActivateCategory(ctx context.Context, arg ActivateCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, activateCategory, arg.ID, arg.Version)
}

const checkCategoriesByParentID = `-- name: CheckCategoriesByParentID :one
SELECT COUNT(*) FROM categories
WHERE parent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CheckCategoriesByParentID(ctx context.Context, parentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCategoriesByParentID, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkNonRetiredCategoriesByParentID = `-- name: CheckNonRetiredCategoriesByParentID :one
WITH RECURSIVE descendants AS (
    SELECT category.id, category.status, category.deleted_at, ARRAY[category.id] AS path
    FROM categories category
    WHERE category.parent_id = $1

    UNION ALL

    SELECT child.id, child.status, child.deleted_at, parent.path || child.id
    FROM categories child
    INNER JOIN descendants parent ON child.parent_id = parent.id
    WHERE NOT child.id = ANY(parent.path)
)
SELECT COUNT(*) FROM descendants
WHERE deleted_at IS NULL AND status <> 'retired'
`

func (q *Queries) CheckNonRetiredCategoriesByParentID(ctx context.Context, parentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkNonRetiredCategoriesByParentID, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, parent_id, name, slug, status, version, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, 'draft', 1, NOW(), NOW(), NULL)
RETURNING id, parent_id, name, slug, status, version, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	ID       uuid.UUID     `json:"id"`
	ParentID uuid.NullUUID `json:"parent_id"`
	Name     string        `json:"name"`
	Slug     string        `json:"slug"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execresult
UPDATE categories AS category
SET deleted_at = NOW(),
    version = version + 1,
    updated_at = NOW()
WHERE category.id = $1
  AND category.status = 'draft'
  AND category.version = $2
  AND category.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM categories child
      WHERE child.parent_id = category.id
        AND child.deleted_at IS NULL
  )
`

type DeleteCategoryParams struct {
	ID      uuid.UUID `json:"id"`
	Version int64     `json:"version"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCategory, arg.ID, arg.Version)
}

const getActiveCategories = `-- name: GetActiveCategories :many
WITH RECURSIVE active_categories AS (
    SELECT id, parent_id, name, slug, status, version, created_at, updated_at, deleted_at, ARRAY[id] AS path
    FROM categories
    WHERE parent_id IS NULL AND status = 'active' AND deleted_at IS NULL

    UNION ALL

    SELECT c.id, c.parent_id, c.name, c.slug, c.status, c.version, c.created_at, c.updated_at, c.deleted_at, parent.path || c.id
    FROM categories c
    INNER JOIN active_categories parent ON c.parent_id = parent.id
    WHERE c.status = 'active' AND c.deleted_at IS NULL AND NOT c.id = ANY(parent.path)
)
SELECT id, parent_id, name, slug, status, version, created_at, updated_at, deleted_at
FROM active_categories
ORDER BY created_at
`

type GetActiveCategoriesRow struct {
	ID        uuid.UUID      `json:"id"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Status    CategoryStatus `json:"status"`
	Version   int64          `json:"version"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetActiveCategories(ctx context.Context) ([]GetActiveCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveCategoriesRow{}
	for rows.Next() {
		var i GetActiveCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveCategoryTreeBySlug = `-- name: GetActiveCategoryTreeBySlug :many
WITH RECURSIVE category_tree AS (
    SELECT categories.id, categories.parent_id, categories.name, categories.slug, categories.status, categories.version, categories.created_at, categories.updated_at, categories.deleted_at, 0 AS depth, ARRAY[categories.id] AS path
    FROM categories
    WHERE categories.slug = $1 AND categories.status = 'active' AND categories.deleted_at IS NULL

    UNION ALL

    SELECT c.id, c.parent_id, c.name, c.slug, c.status, c.version, c.created_at, c.updated_at, c.deleted_at, ct.depth + 1, ct.path || c.id
    FROM categories c
    INNER JOIN category_tree ct ON c.parent_id = ct.id
    WHERE c.status = 'active' AND c.deleted_at IS NULL AND NOT c.id = ANY(ct.path)
)
SELECT id, parent_id, name, slug, status, version, created_at, updated_at, deleted_at
FROM category_tree
ORDER BY depth, created_at
`

type GetActiveCategoryTreeBySlugRow struct {
	ID        uuid.UUID      `json:"id"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Status    CategoryStatus `json:"status"`
	Version   int64          `json:"version"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetActiveCategoryTreeBySlug(ctx context.Context, slug string) ([]GetActiveCategoryTreeBySlugRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveCategoryTreeBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveCategoryTreeBySlugRow{}
	for rows.Next() {
		var i GetActiveCategoryTreeBySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, parent_id, name, slug, status, version, created_at, updated_at, deleted_at
FROM categories
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, parent_id, name, slug, status, version, created_at, updated_at, deleted_at
FROM categories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, parent_id, name, slug, status, version, created_at, updated_at, deleted_at
FROM categories
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryTreeBySlug = `-- name: GetCategoryTreeBySlug :many
WITH RECURSIVE category_tree AS (
    SELECT categories.id, categories.parent_id, categories.name, categories.slug, categories.status, categories.version, categories.created_at, categories.updated_at, categories.deleted_at, 0 AS depth, ARRAY[categories.id] AS path
    FROM categories
    WHERE categories.slug = $1 AND categories.deleted_at IS NULL

    UNION ALL

    SELECT c.id, c.parent_id, c.name, c.slug, c.status, c.version, c.created_at, c.updated_at, c.deleted_at, ct.depth + 1, ct.path || c.id
    FROM categories c
    INNER JOIN category_tree ct ON c.parent_id = ct.id
    WHERE c.deleted_at IS NULL AND NOT c.id = ANY(ct.path)
)
SELECT id, parent_id, name, slug, status, version, created_at, updated_at, deleted_at
FROM category_tree
ORDER BY depth, created_at
`

type GetCategoryTreeBySlugRow struct {
	ID        uuid.UUID      `json:"id"`
	ParentID  uuid.NullUUID  `json:"parent_id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Status    CategoryStatus `json:"status"`
	Version   int64          `json:"version"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetCategoryTreeBySlug(ctx context.Context, slug string) ([]GetCategoryTreeBySlugRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryTreeBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryTreeBySlugRow{}
	for rows.Next() {
		var i GetCategoryTreeBySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireCategory = `-- name: RetireCategory :execresult
WITH RECURSIVE descendants AS (
    SELECT child.id, child.status, child.deleted_at, ARRAY[child.id] AS path
    FROM categories child
    WHERE child.parent_id = $1

    UNION ALL

    SELECT child.id, child.status, child.deleted_at, parent.path || child.id
    FROM categories child
    INNER JOIN descendants parent ON child.parent_id = parent.id
    WHERE NOT child.id = ANY(parent.path)
)
UPDATE categories AS category
SET status = 'retired',
    version = version + 1,
    updated_at = NOW()
WHERE category.id = $1
  AND category.status = 'active'
  AND category.version = $2
  AND category.deleted_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM descendants WHERE descendants.deleted_at IS NULL AND descendants.status <> 'retired')
`

type RetireCategoryParams struct {
	ID      uuid.UUID `json:"id"`
	Version int64     `json:"version"`
}

func (q *Queries) RetireCategory(ctx context.Context, arg RetireCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, retireCategory, arg.ID, arg.Version)
}

const updateCategory = `-- name: UpdateCategory :one
WITH RECURSIVE ancestors AS (
    SELECT id, parent_id, ARRAY[id] AS path
    FROM categories
    WHERE id = $2 AND $2 IS NOT NULL AND deleted_at IS NULL

    UNION ALL

    SELECT parent.id, parent.parent_id, child.path || parent.id
    FROM categories parent
    INNER JOIN ancestors child ON parent.id = child.parent_id
    WHERE parent.deleted_at IS NULL AND NOT parent.id = ANY(child.path)
)
UPDATE categories AS category
SET parent_id = $2,
    name = $3,
    slug = $4,
    version = version + 1,
    updated_at = NOW()
WHERE category.id = $1
  AND category.status = 'draft'
  AND category.version = $5
  AND category.deleted_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM ancestors WHERE ancestors.id = $1)
RETURNING category.id, category.parent_id, category.name, category.slug, category.status, category.version, category.created_at, category.updated_at, category.deleted_at
`

type UpdateCategoryParams struct {
	ID       uuid.UUID     `json:"id"`
	ParentID uuid.NullUUID `json:"parent_id"`
	Name     string        `json:"name"`
	Slug     string        `json:"slug"`
	Version  int64         `json:"version"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Version,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
