// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brand.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBrand = `-- name: CreateBrand :exec
INSERT INTO brands (id, name, slug, logo_path, is_active, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, TRUE, NOW(), NOW(), NULL)
`

type CreateBrandParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Slug     string    `json:"slug"`
	LogoPath *string   `json:"logo_path"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) error {
	_, err := q.db.ExecContext(ctx, createBrand,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.LogoPath,
	)
	return err
}

const deleteBrand = `-- name: DeleteBrand :execresult
UPDATE brands
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteBrand(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteBrand, id)
}

const getAllBrands = `-- name: GetAllBrands :many
SELECT id, name, slug, logo_path, is_active, created_at, updated_at, deleted_at
FROM brands
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.QueryContext(ctx, getAllBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Brand{}
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoPath,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBrandBySlug = `-- name: GetBrandBySlug :one
SELECT id, name, slug, logo_path, is_active, created_at, updated_at, deleted_at
FROM brands
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBrandBySlug(ctx context.Context, slug string) (Brand, error) {
	row := q.db.QueryRowContext(ctx, getBrandBySlug, slug)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoPath,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBrand = `-- name: UpdateBrand :exec
UPDATE brands
SET name = $2,
    slug = $3,
    logo_path = $4,
    is_active = $5,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateBrandParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Slug     string    `json:"slug"`
	LogoPath *string   `json:"logo_path"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) error {
	_, err := q.db.ExecContext(ctx, updateBrand,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.LogoPath,
		arg.IsActive,
	)
	return err
}

const updateBrandLogo = `-- name: UpdateBrandLogo :execresult
UPDATE brands
SET logo_path  = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateBrandLogoParams struct {
	ID       uuid.UUID `json:"id"`
	LogoPath *string   `json:"logo_path"`
}

func (q *Queries) UpdateBrandLogo(ctx context.Context, arg UpdateBrandLogoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBrandLogo, arg.ID, arg.LogoPath)
}
