// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_image.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (id, product_id, url, alt_text, position, is_primary, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, product_id, url, alt_text, position, is_primary, created_at, updated_at
`

type CreateProductImageParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	Url       string    `json:"url"`
	AltText   *string   `json:"alt_text"`
	Position  int16     `json:"position"`
	IsPrimary bool      `json:"is_primary"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, createProductImage,
		arg.ID,
		arg.ProductID,
		arg.Url,
		arg.AltText,
		arg.Position,
		arg.IsPrimary,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.Position,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :execresult
DELETE FROM product_images
WHERE product_id = $1 AND id = $2
`

type DeleteProductImageParams struct {
	ProductID uuid.UUID `json:"product_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeleteProductImage(ctx context.Context, arg DeleteProductImageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProductImage, arg.ProductID, arg.ID)
}

const getProductImageByID = `-- name: GetProductImageByID :one
SELECT id, product_id, url, alt_text, position, is_primary, created_at, updated_at
FROM product_images
WHERE id = $1
`

func (q *Queries) GetProductImageByID(ctx context.Context, id uuid.UUID) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, getProductImageByID, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.Position,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductImagesByProductID = `-- name: GetProductImagesByProductID :many
SELECT id, product_id, url, alt_text, position, is_primary, created_at, updated_at
FROM product_images
WHERE product_id = $1
ORDER BY is_primary DESC, position ASC, created_at ASC
`

func (q *Queries) GetProductImagesByProductID(ctx context.Context, productID uuid.UUID) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, getProductImagesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.AltText,
			&i.Position,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryImage = `-- name: SetPrimaryImage :execresult
UPDATE product_images AS image
SET is_primary = CASE WHEN image.id = $2 THEN TRUE ELSE FALSE END,
    updated_at = NOW()
WHERE image.product_id = $1
  AND EXISTS (
      SELECT 1
      FROM product_images target
      WHERE target.id = $2 AND target.product_id = $1
  )
`

type SetPrimaryImageParams struct {
	ProductID uuid.UUID `json:"product_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetPrimaryImage(ctx context.Context, arg SetPrimaryImageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setPrimaryImage, arg.ProductID, arg.ID)
}
