// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (id, name, slug, description, short_description, status, brand_id, is_featured, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW(), NULL)
`

type CreateProductParams struct {
	ID               uuid.UUID     `json:"id"`
	Name             string        `json:"name"`
	Slug             string        `json:"slug"`
	Description      *string       `json:"description"`
	ShortDescription *string       `json:"short_description"`
	Status           ProductStatus `json:"status"`
	BrandID          *uuid.UUID    `json:"brand_id"`
	IsFeatured       bool          `json:"is_featured"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ShortDescription,
		arg.Status,
		arg.BrandID,
		arg.IsFeatured,
	)
	return err
}

const deleteProduct = `-- name: DeleteProduct :execresult
UPDATE products
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProduct, id)
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, name, slug, description, short_description, brand_id, status, is_featured, created_at, updated_at, deleted_at
FROM products
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.BrandID,
			&i.Status,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductDetailByID = `-- name: GetProductDetailByID :many
SELECT
    p.id,
    p.name,
    p.slug,
    p.description,
    p.short_description,
    p.brand_id,
    p.status,
    p.is_featured,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    po.id          AS option_id,
    po.name        AS option_name,
    po.position    AS option_position,
    po.is_active   AS option_is_active,
    po.created_at  AS option_created_at,
    po.updated_at  AS option_updated_at,
    pov.id         AS value_id,
    pov.value      AS value_text,
    pov.position   AS value_position,
    pov.is_active  AS value_is_active,
    pov.created_at AS value_created_at,
    pov.updated_at AS value_updated_at
FROM products p
LEFT JOIN product_options po
    ON po.product_id = p.id
    AND po.deleted_at IS NULL
    AND po.is_active = TRUE
LEFT JOIN product_option_values pov
    ON pov.product_option_id = po.id
    AND pov.deleted_at IS NULL
    AND pov.is_active = TRUE
WHERE p.id = $1
  AND p.deleted_at IS NULL
ORDER BY po.position ASC, po.created_at ASC, pov.position ASC, pov.created_at ASC
`

type GetProductDetailByIDRow struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Description      *string        `json:"description"`
	ShortDescription *string        `json:"short_description"`
	BrandID          *uuid.UUID     `json:"brand_id"`
	Status           ProductStatus  `json:"status"`
	IsFeatured       bool           `json:"is_featured"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        *time.Time     `json:"deleted_at"`
	OptionID         uuid.NullUUID  `json:"option_id"`
	OptionName       sql.NullString `json:"option_name"`
	OptionPosition   sql.NullInt16  `json:"option_position"`
	OptionIsActive   sql.NullBool   `json:"option_is_active"`
	OptionCreatedAt  sql.NullTime   `json:"option_created_at"`
	OptionUpdatedAt  sql.NullTime   `json:"option_updated_at"`
	ValueID          uuid.NullUUID  `json:"value_id"`
	ValueText        sql.NullString `json:"value_text"`
	ValuePosition    sql.NullInt16  `json:"value_position"`
	ValueIsActive    sql.NullBool   `json:"value_is_active"`
	ValueCreatedAt   sql.NullTime   `json:"value_created_at"`
	ValueUpdatedAt   sql.NullTime   `json:"value_updated_at"`
}

func (q *Queries) GetProductDetailByID(ctx context.Context, id uuid.UUID) ([]GetProductDetailByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductDetailByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductDetailByIDRow{}
	for rows.Next() {
		var i GetProductDetailByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.BrandID,
			&i.Status,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OptionID,
			&i.OptionName,
			&i.OptionPosition,
			&i.OptionIsActive,
			&i.OptionCreatedAt,
			&i.OptionUpdatedAt,
			&i.ValueID,
			&i.ValueText,
			&i.ValuePosition,
			&i.ValueIsActive,
			&i.ValueCreatedAt,
			&i.ValueUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductDetailBySlug = `-- name: GetProductDetailBySlug :many
SELECT
    p.id,
    p.name,
    p.slug,
    p.description,
    p.short_description,
    p.brand_id,
    p.status,
    p.is_featured,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    po.id          AS option_id,
    po.name        AS option_name,
    po.position    AS option_position,
    po.is_active   AS option_is_active,
    po.created_at  AS option_created_at,
    po.updated_at  AS option_updated_at,
    pov.id         AS value_id,
    pov.value      AS value_text,
    pov.position   AS value_position,
    pov.is_active  AS value_is_active,
    pov.created_at AS value_created_at,
    pov.updated_at AS value_updated_at
FROM products p
LEFT JOIN product_options po
    ON po.product_id = p.id
    AND po.deleted_at IS NULL
    AND po.is_active = TRUE
LEFT JOIN product_option_values pov
    ON pov.product_option_id = po.id
    AND pov.deleted_at IS NULL
    AND pov.is_active = TRUE
WHERE p.slug = $1
  AND p.deleted_at IS NULL
ORDER BY po.position ASC, po.created_at ASC, pov.position ASC, pov.created_at ASC
`

type GetProductDetailBySlugRow struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Description      *string        `json:"description"`
	ShortDescription *string        `json:"short_description"`
	BrandID          *uuid.UUID     `json:"brand_id"`
	Status           ProductStatus  `json:"status"`
	IsFeatured       bool           `json:"is_featured"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        *time.Time     `json:"deleted_at"`
	OptionID         uuid.NullUUID  `json:"option_id"`
	OptionName       sql.NullString `json:"option_name"`
	OptionPosition   sql.NullInt16  `json:"option_position"`
	OptionIsActive   sql.NullBool   `json:"option_is_active"`
	OptionCreatedAt  sql.NullTime   `json:"option_created_at"`
	OptionUpdatedAt  sql.NullTime   `json:"option_updated_at"`
	ValueID          uuid.NullUUID  `json:"value_id"`
	ValueText        sql.NullString `json:"value_text"`
	ValuePosition    sql.NullInt16  `json:"value_position"`
	ValueIsActive    sql.NullBool   `json:"value_is_active"`
	ValueCreatedAt   sql.NullTime   `json:"value_created_at"`
	ValueUpdatedAt   sql.NullTime   `json:"value_updated_at"`
}

func (q *Queries) GetProductDetailBySlug(ctx context.Context, slug string) ([]GetProductDetailBySlugRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductDetailBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductDetailBySlugRow{}
	for rows.Next() {
		var i GetProductDetailBySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.BrandID,
			&i.Status,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OptionID,
			&i.OptionName,
			&i.OptionPosition,
			&i.OptionIsActive,
			&i.OptionCreatedAt,
			&i.OptionUpdatedAt,
			&i.ValueID,
			&i.ValueText,
			&i.ValuePosition,
			&i.ValueIsActive,
			&i.ValueCreatedAt,
			&i.ValueUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = $2,
    slug = $3,
    description = $4,
    short_description = $5,
    status = $6,
    brand_id = $7,
    is_featured = $8,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateProductParams struct {
	ID               uuid.UUID     `json:"id"`
	Name             string        `json:"name"`
	Slug             string        `json:"slug"`
	Description      *string       `json:"description"`
	ShortDescription *string       `json:"short_description"`
	Status           ProductStatus `json:"status"`
	BrandID          *uuid.UUID    `json:"brand_id"`
	IsFeatured       bool          `json:"is_featured"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ShortDescription,
		arg.Status,
		arg.BrandID,
		arg.IsFeatured,
	)
	return err
}
