// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_option.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const bulkCreateProductOptionValues = `-- name: BulkCreateProductOptionValues :many
INSERT INTO product_option_values (id, product_option_id, value, position, is_active, created_at, updated_at)
SELECT
    UNNEST($1::uuid[]),
    $2::uuid,
    UNNEST($3::varchar[]),
    UNNEST($4::smallint[]),
    UNNEST($5::boolean[]),
    NOW(),
    NOW()
RETURNING id, product_option_id, value, position, is_active, created_at, updated_at, deleted_at
`

type BulkCreateProductOptionValuesParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 uuid.UUID   `json:"column_2"`
	Column3 []string    `json:"column_3"`
	Column4 []int16     `json:"column_4"`
	Column5 []bool      `json:"column_5"`
}

func (q *Queries) BulkCreateProductOptionValues(ctx context.Context, arg BulkCreateProductOptionValuesParams) ([]ProductOptionValue, error) {
	rows, err := q.db.QueryContext(ctx, bulkCreateProductOptionValues,
		pq.Array(arg.Column1),
		arg.Column2,
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
		pq.Array(arg.Column5),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductOptionValue{}
	for rows.Next() {
		var i ProductOptionValue
		if err := rows.Scan(
			&i.ID,
			&i.ProductOptionID,
			&i.Value,
			&i.Position,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProductOption = `-- name: CreateProductOption :one

INSERT INTO product_options (id, product_id, name, position, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, product_id, name, position, is_active, created_at, updated_at, deleted_at
`

type CreateProductOptionParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	Name      string    `json:"name"`
	Position  int16     `json:"position"`
	IsActive  bool      `json:"is_active"`
}

// -------------------------------------------------------
// product_options
// -------------------------------------------------------
func (q *Queries) CreateProductOption(ctx context.Context, arg CreateProductOptionParams) (ProductOption, error) {
	row := q.db.QueryRowContext(ctx, createProductOption,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Position,
		arg.IsActive,
	)
	var i ProductOption
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProductOptionValue = `-- name: CreateProductOptionValue :one

INSERT INTO product_option_values (id, product_option_id, value, position, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, product_option_id, value, position, is_active, created_at, updated_at, deleted_at
`

type CreateProductOptionValueParams struct {
	ID              uuid.UUID `json:"id"`
	ProductOptionID uuid.UUID `json:"product_option_id"`
	Value           string    `json:"value"`
	Position        int16     `json:"position"`
	IsActive        bool      `json:"is_active"`
}

// -------------------------------------------------------
// product_option_values
// -------------------------------------------------------
func (q *Queries) CreateProductOptionValue(ctx context.Context, arg CreateProductOptionValueParams) (ProductOptionValue, error) {
	row := q.db.QueryRowContext(ctx, createProductOptionValue,
		arg.ID,
		arg.ProductOptionID,
		arg.Value,
		arg.Position,
		arg.IsActive,
	)
	var i ProductOptionValue
	err := row.Scan(
		&i.ID,
		&i.ProductOptionID,
		&i.Value,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProductOption = `-- name: DeleteProductOption :execresult
UPDATE product_options
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteProductOption(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProductOption, id)
}

const deleteProductOptionValue = `-- name: DeleteProductOptionValue :execresult
UPDATE product_option_values
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteProductOptionValue(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProductOptionValue, id)
}

const getProductOptionByID = `-- name: GetProductOptionByID :one
SELECT id, product_id, name, position, is_active, created_at, updated_at, deleted_at
FROM product_options
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProductOptionByID(ctx context.Context, id uuid.UUID) (ProductOption, error) {
	row := q.db.QueryRowContext(ctx, getProductOptionByID, id)
	var i ProductOption
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductOptionValueByID = `-- name: GetProductOptionValueByID :one
SELECT id, product_option_id, value, position, is_active, created_at, updated_at, deleted_at
FROM product_option_values
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProductOptionValueByID(ctx context.Context, id uuid.UUID) (ProductOptionValue, error) {
	row := q.db.QueryRowContext(ctx, getProductOptionValueByID, id)
	var i ProductOptionValue
	err := row.Scan(
		&i.ID,
		&i.ProductOptionID,
		&i.Value,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductOptionValuesByOptionID = `-- name: GetProductOptionValuesByOptionID :many
SELECT id, product_option_id, value, position, is_active, created_at, updated_at, deleted_at
FROM product_option_values
WHERE product_option_id = $1
  AND deleted_at IS NULL
ORDER BY position ASC, created_at ASC
`

func (q *Queries) GetProductOptionValuesByOptionID(ctx context.Context, productOptionID uuid.UUID) ([]ProductOptionValue, error) {
	rows, err := q.db.QueryContext(ctx, getProductOptionValuesByOptionID, productOptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductOptionValue{}
	for rows.Next() {
		var i ProductOptionValue
		if err := rows.Scan(
			&i.ID,
			&i.ProductOptionID,
			&i.Value,
			&i.Position,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductOptionsByProductID = `-- name: GetProductOptionsByProductID :many
SELECT id, product_id, name, position, is_active, created_at, updated_at, deleted_at
FROM product_options
WHERE product_id = $1
  AND deleted_at IS NULL
ORDER BY position ASC, created_at ASC
`

func (q *Queries) GetProductOptionsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductOption, error) {
	rows, err := q.db.QueryContext(ctx, getProductOptionsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductOption{}
	for rows.Next() {
		var i ProductOption
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Position,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductOption = `-- name: UpdateProductOption :one
UPDATE product_options
SET name       = $2,
    position   = $3,
    is_active  = $4,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, product_id, name, position, is_active, created_at, updated_at, deleted_at
`

type UpdateProductOptionParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Position int16     `json:"position"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateProductOption(ctx context.Context, arg UpdateProductOptionParams) (ProductOption, error) {
	row := q.db.QueryRowContext(ctx, updateProductOption,
		arg.ID,
		arg.Name,
		arg.Position,
		arg.IsActive,
	)
	var i ProductOption
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
