// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkActiveCategoriesByParentId = `-- name: CheckActiveCategoriesByParentId :one
SELECT COUNT(*) FROM categories
WHERE parent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CheckActiveCategoriesByParentId(ctx context.Context, parentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkActiveCategoriesByParentId, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (id, parent_id,name, slug, is_active, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3,$4,TRUE, NOW(), NOW(), NULL)
`

type CreateCategoryParams struct {
	ID       uuid.UUID     `json:"id"`
	ParentID uuid.NullUUID `json:"parent_id"`
	Name     string        `json:"name"`
	Slug     string        `json:"slug"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :execresult
UPDATE categories
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCategory, id)
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, parent_id, name, slug, is_active, created_at, updated_at, deleted_at
FROM categories
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, parent_id, name, slug, is_active, created_at, updated_at, deleted_at
FROM categories
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryTreeBySlug = `-- name: GetCategoryTreeBySlug :many
WITH RECURSIVE category_tree AS (
    SELECT categories.id, categories.parent_id, categories.name, categories.slug, categories.is_active, categories.created_at, categories.updated_at, categories.deleted_at
    FROM categories
    WHERE categories.slug = $1 AND categories.deleted_at IS NULL

    UNION ALL

    SELECT c.id, c.parent_id, c.name, c.slug, c.is_active, c.created_at, c.updated_at, c.deleted_at
    FROM categories c
    INNER JOIN category_tree ct ON c.parent_id = ct.id
    WHERE c.deleted_at IS NULL
)
SELECT id, parent_id, name, slug, is_active, created_at, updated_at, deleted_at FROM category_tree
`

type GetCategoryTreeBySlugRow struct {
	ID        uuid.UUID     `json:"id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	Name      string        `json:"name"`
	Slug      string        `json:"slug"`
	IsActive  bool          `json:"is_active"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
}

func (q *Queries) GetCategoryTreeBySlug(ctx context.Context, slug string) ([]GetCategoryTreeBySlugRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryTreeBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryTreeBySlugRow{}
	for rows.Next() {
		var i GetCategoryTreeBySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
SET parent_id = $2,
    name = $3,
    slug = $4,
    is_active = $5,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateCategoryParams struct {
	ID       uuid.UUID     `json:"id"`
	ParentID uuid.NullUUID `json:"parent_id"`
	Name     string        `json:"name"`
	Slug     string        `json:"slug"`
	IsActive bool          `json:"is_active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.IsActive,
	)
	return err
}
